### ISSUE TITLE
Fix/downgrade `lint-staged`

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/wp-scaffold#161]
### Describe the bug

`lint-staged` version 13 introduced on #140 seems to be using ESM and it's erroring locally for some people. 

Investigate or downgrade to `11.2.6`

```
[2022-08-26T15:41:46.167Z] internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/foo/10up/clients/test/wordpress/wp-content/node_modules/lint-staged/bin/lint-staged.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
husky - pre-commit hook exited with code 1 (error)
``` 

### Steps to Reproduce

Triggering the lint-staged from a commit should make this appear.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
@Antonio-Laguna I don't think this is valid anymore. Closing for now. Feel free to reopen if needed
